#!/bin/bash

set -e

for (( i=0; i<20; i++ )) ; do
  curl -s -o /dev/null http://$TIDDLYWIKI_HOST:9091 && break
  sleep 1
done

if [[ $i -eq 20 ]] ; then
    echo "failed to connect to test server after 20 tries" >&2
    exit 1
fi

export ELECTRON_ENABLE_LOGGING=1
cat weird-urls.txt | while read url ; do
    # XXX if we already have a record for $url, skip
    # XXX enable debug logging in the client/server
    CYPRESS_TIDDLYWIKI_TARGET_URL="$url" CYPRESS_TIDDLYWIKI_HOST=$TIDDLYWIKI_HOST cypress run &> report.txt
    ls cypress/videos/
    # XXX move video/logs into record for $url, commit to long-term storage
done
