export PLUGIN_TITLE=hoelzro/first-class-urls/log-routes
export PLUGIN_NAME=Log Access For First Class URLs
export PLUGIN_DESCRIPTION=Log Access For First Class URLs
export PLUGIN_AUTHOR=RobHoelz
export PLUGIN_CORE_VERSION=5.1.22
export PLUGIN_SOURCE=https://github.com/hoelzro/tw-first-class-urls

build:
	make -f ../tw-plugin-builder/Makefile build

clean:
	make -f ../tw-plugin-builder/Makefile clean
