name: Tests
on:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 15
    - run: |-
        git submodule init
        git submodule update
        npm install
        make build
        make test
