name: Tests
on:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: cypress-io/github-action@v2
      with:
        build: ./build
        start: ./serve
        wait-on: http://localhost:9091
