name: Tests
on:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 1
    strategy:
      matrix:
        node:
        - 14
        - 15
        tiddlywiki:
        - tiddlywiki@5.1.21
        - tiddlywiki@5.1.22
        - tiddlywiki@5.1.23
        - https://github.com/Jermolene/TiddlyWiki5.git
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: |-
        git submodule init
        git submodule update
        npm install
        npm install ${{ matrix.tiddlywiki }}
        make build
        make test
