name: Tests
on:
  push:
    branches:
    - main
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: |-
        git submodule init
        git submodule update
        npm install
        make build
        make test
