name: Tests
on:
  push:
    branches:
    - main
jobs:
  test:
    permissions:
      contents: none
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    strategy:
      matrix:
        node:
        - 14
        - 15
        - 16
        tiddlywiki:
        - tiddlywiki@5.1.21
        - tiddlywiki@5.1.22
        - tiddlywiki@5.1.23
        - https://github.com/Jermolene/TiddlyWiki5.git
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: |-
        git submodule init
        git submodule update
        npm install --production
        npm install --production ${{ matrix.tiddlywiki }}
        make build
        make test
  cypress-test:
    permissions:
      contents: none
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    strategy:
      matrix:
        node:
        - 14
        - 15
        - 16
        tiddlywiki:
        - tiddlywiki@5.1.21
        - tiddlywiki@5.1.22
        - tiddlywiki@5.1.23
        - https://github.com/Jermolene/TiddlyWiki5.git
    steps:
    - name: install-jq
      run: |-
        mkdir -p $HOME/bin
        curl -s -Lo $HOME/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
        chmod 755 $HOME/bin/jq
        echo "$HOME/bin" >> $GITHUB_PATH
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: run-server
      run: |-
        git submodule init
        git submodule update
        npm install --production
        npm install --production ${{ matrix.tiddlywiki }}
        make build
        ip addr show docker0 | perl -nle 'if(my ( $addr ) = /inet\s+([.\d]+)/) { print "TIDDLYWIKI_HOST=$addr"; last }' >> $GITHUB_ENV
        TIDDLYWIKI_HOST=0.0.0.0 bash serve-temp-wiki &
    - name: run-tests
      uses: docker://cypress/included:5.6.0
      with:
        entrypoint: ./run-cypress-tests.sh
  eslint:
    permissions:
      contents: none
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: |-
        npx eslint .
