name: weird-urls
on:
  push:
    branches:
    - perm-experiment
jobs:
  gather-the-weird:
    permissions:
      statuses: write
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: try-push
      run:
        git push origin HEAD:test-target
